### ISSUE TITLE
Review buy UX

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments#24]
A first pass of the purchase UX was done in 2014, this is to review that, tighten it up, strip out any extra material, add in new screens etc.

**Comment by kumar303** [comment]
aforementioned purchase UX is here http://payments.readthedocs.org/en/latest/design/ux.html#purchase-flow

**Comment by brampitoyo** [comment]
I’ve updated the new buy mockups and flow to reflect a few new things:
- Insufficient funds
  - Other error messages (invalid CVV, card number, expiry date, etc.) has to do with credit card and can be handled inside the add credit card form
- FxA onboarding – save payment information
  - To be able to subscribe, payment information must be saved. Therefore, user must sign in and have an account.
  - For one-off purchases, an account isn’t necessary.

![fxa payments - buy flow](https://cloud.githubusercontent.com/assets/51007/7386507/09f5e98e-eea9-11e4-8d1a-3b495d8cfe74.png)

![fxa payments - buy wireframes](https://cloud.githubusercontent.com/assets/51007/7386508/0f9ef33a-eea9-11e4-88de-25efa8a4a4e0.png)

**Comment by kumar303** [comment]
Actually, I think an account is required for one-off purchases because we intend to use FxA to prove ownership of the product. For example, when the user returns to Mozilla Concrete to start using the fresh mortar they just subscribed to, they will first need to login to FxA so that Mozilla Concrete can check if they own a mortar subscription or not.

**Comment by brampitoyo** [comment]
> Actually, I think an account is required for one-off purchases

My original intention is to remove any barrier to purchase as much as possible. This means not putting a sign in/registration form in front of the flow. So a user can purchase something with nothing else but a credit card and an email address.

If she wants to save the credit card for next time, she’ll have to create a password, of course. But this comes after the payment confirmation.

We might be able to substitute email address with phone number, for example: any place to send the receipt to would work.

On the other hand, whenever the product requires user to sign into a specific account in order for it to activate, the buy flow should require user to sign in/register first.

So maybe the distinction isn’t between one-off and subscription. Rather, it’s between products that need an account in order to work properly, and products that don’t.

**Comment by andymckay** [comment]
That's a good point, we could conceivably have a product that never needs the proof, in which case the fastest way possible would be great. That's not on the roadmap that I know of yet though.
