### ISSUE TITLE
Full-screen error for critical errors.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/payments#70]
We're going to need a full-screen error that the user will see when something critical fails.

An example would be requesting the braintree token or login failure. Some of these things might be able to have a retry.

**Comment by brampitoyo** [comment]
When an error isn’t related to any form field, we should keep the “Subscribe/Buy” button enabled but put a warning flag on top of it. The flag will say “There’s an error processing your card. Try again in a minute or two”.

The reason why I don’t want to disable the button is because it’s not the user’s fault, but the system’s. The payment information is correct, after all, so the user should be able to retry again and again if she wants to.

Would this apply to your error scenario (requesting braintree token, login failure), or not quite?

The only scenario where disabling the button is a good idea is when the error requires form fields to be modified. For example, if my credit card is expired or CVV is incorrect. In these scenarios, the button is disabled until the value inside the problematic form field (highlighted in red) is modified.

> the UX for this shows the message dissappearing after 2 secs. Do you think we could change that and make it go on top of the form fields and stay there until - resubmitting or a value is changed by the user.

I worry that putting the error flag far away from the relevant form field or button might make user miss it.

However, making the error persistent is a great idea!

And just in case we need a full-screen error for critical failures, here are two potential designs for it. What do you think?

![critical-error-1](https://cloud.githubusercontent.com/assets/51007/8029544/925ecaba-0e12-11e5-9f4e-ca5a2d1f1ca0.PNG)
![critical-error-2](https://cloud.githubusercontent.com/assets/51007/8029606/35c31102-0e13-11e5-9af7-682dd3071125.PNG)

**Comment by kumar303** [comment]
A full screen of red might feel like instant death ;) If that's too intense, perhaps just a blank screen with the red error bar in the middle?

**Comment by muffinresearch** [comment]
I agree the red screen is a bit scary! 

The problems that a full-screen error is required for is more things that are before you even get to the card-form. E.g. Login failed - (After FXA when the user is verifying the login token provided)

The other reason why it's needed is when something goes wrong e.g. a service is temporarily down. We'll want a retry for that case. Whilst if this is on the card screen you _could_ re-use the form submit, but elsewhere we'll need a distinct button to retry the request because that page would otherwise be a spinner with no other UI (e.g. the login failure example).

**Comment by muffinresearch** [comment]
Note the other issue relating to this subject is here: https://github.com/mozilla/payments-ui/issues/80

**Comment by brampitoyo** [comment]
> If that's too intense, perhaps just a blank screen with the red error bar in the middle?

What about a simple red text on top of a white background (if using a separate screen) like this?
![full-screen-error](https://cloud.githubusercontent.com/assets/51007/8153117/6ea080fe-137c-11e5-87af-e18d50b5f4f1.png)

We can use the same technique and apply it to an overlay – no more red screen of death – like so:
![full-screen-error-overlay](https://cloud.githubusercontent.com/assets/51007/8153197/1c349ed4-137e-11e5-96bb-afc79b420ee1.png)

Unfortunately, a single red flag in the middle of the box doesn’t look visually balanced.
![full-screen-error-flag](https://cloud.githubusercontent.com/assets/51007/8153141/e78fb19c-137c-11e5-84fe-ef49182c2e40.png)

What do you think?

**Comment by kumar303** [comment]
Awesome! I like the red text on a dimmed white background

**Comment by andymckay** [comment]
Same, middle one for me is the winner.

**Comment by brampitoyo** [comment]
Awesome. I used the same red in our error flag (#d83812), and the same text size and style as product name. The white overlay has an opacity value of 0.94.

**Comment by muffinresearch** [comment]
Ok I  think this is good for now. We just to open up more bugs for error cases we don't currently handle.
